// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_paste_input {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class PasteInputHostApi;
  friend class PasteInputFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Represents a single item from the clipboard.
//
// Each item contains raw binary data and its MIME type,
// allowing Flutter to determine how to handle the content.
//
// Generated class from Pigeon that represents data sent in messages.
class ClipboardItem {
 public:
  // Constructs an object setting all fields.
  explicit ClipboardItem(
    const std::vector<uint8_t>& data,
    const std::string& mime_type);

  // Raw binary data of the clipboard item.
  //
  // For images, this contains the image bytes (PNG, JPEG, GIF, etc.).
  // For text, this contains the UTF-8 encoded string bytes.
  const std::vector<uint8_t>& data() const;
  void set_data(const std::vector<uint8_t>& value_arg);

  // MIME type of the clipboard item.
  //
  // Common values:
  // - "text/plain" for plain text
  // - "image/png" for PNG images
  // - "image/jpeg" for JPEG images
  // - "image/gif" for GIF images
  // - "image/webp" for WebP images
  const std::string& mime_type() const;
  void set_mime_type(std::string_view value_arg);


 private:
  static ClipboardItem FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasteInputHostApi;
  friend class PasteInputFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::vector<uint8_t> data_;
  std::string mime_type_;

};


// Represents the complete clipboard content.
//
// The clipboard may contain multiple items of different types.
// For example, copying an image might also include a text representation.
//
// Generated class from Pigeon that represents data sent in messages.
class ClipboardContent {
 public:
  // Constructs an object setting all fields.
  explicit ClipboardContent(const flutter::EncodableList& items);

  // List of clipboard items.
  //
  // May be empty if the clipboard is empty or contains unsupported content.
  const flutter::EncodableList& items() const;
  void set_items(const flutter::EncodableList& value_arg);


 private:
  static ClipboardContent FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasteInputHostApi;
  friend class PasteInputFlutterApi;
  friend class PigeonInternalCodecSerializer;
  flutter::EncodableList items_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Host API for clipboard operations (Dart -> Native).
//
// This API is implemented by each platform's native code and called from Dart.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class PasteInputHostApi {
 public:
  PasteInputHostApi(const PasteInputHostApi&) = delete;
  PasteInputHostApi& operator=(const PasteInputHostApi&) = delete;
  virtual ~PasteInputHostApi() {}
  // Retrieves the current clipboard content.
  //
  // Returns a [ClipboardContent] containing all available clipboard items.
  // The items are returned with their raw data and MIME types, allowing
  // the Dart side to determine how to process them.
  //
  // Returns an empty [ClipboardContent] if the clipboard is empty or
  // contains only unsupported content types.
  virtual ErrorOr<ClipboardContent> GetClipboardContent() = 0;
  // Clears temporary files created during paste operations.
  //
  // Call this periodically to free up disk space. Paste operations may
  // create temporary files when handling image content.
  virtual std::optional<FlutterError> ClearTempFiles() = 0;
  // Returns the platform version string.
  //
  // Useful for debugging and platform-specific behavior.
  // Example: "Android 14", "iOS 17.0", "macOS 14.0"
  virtual ErrorOr<std::string> GetPlatformVersion() = 0;

  // The codec used by PasteInputHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `PasteInputHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PasteInputHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PasteInputHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  PasteInputHostApi() = default;

};
// Flutter API for paste event notifications (Native -> Dart).
//
// This API is implemented in Dart and called from native code when
// paste events are detected (e.g., through keyboard shortcuts or
// context menu actions).
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class PasteInputFlutterApi {
 public:
  PasteInputFlutterApi(flutter::BinaryMessenger* binary_messenger);
  PasteInputFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  // Called when a paste event is detected on the native side.
  //
  // The [content] parameter contains the clipboard content at the time
  // of the paste event. This allows Flutter to handle the pasted content
  // immediately without additional clipboard reads.
  void OnPasteDetected(
    const ClipboardContent& content,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace flutter_paste_input
#endif  // PIGEON_MESSAGES_G_H_
