// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Represents a single item from the clipboard.
///
/// Each item contains raw binary data and its MIME type,
/// allowing Flutter to determine how to handle the content.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ClipboardItem {
  /// Raw binary data of the clipboard item.
  ///
  /// For images, this contains the image bytes (PNG, JPEG, GIF, etc.).
  /// For text, this contains the UTF-8 encoded string bytes.
  var data: FlutterStandardTypedData
  /// MIME type of the clipboard item.
  ///
  /// Common values:
  /// - "text/plain" for plain text
  /// - "image/png" for PNG images
  /// - "image/jpeg" for JPEG images
  /// - "image/gif" for GIF images
  /// - "image/webp" for WebP images
  var mimeType: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClipboardItem? {
    let data = pigeonVar_list[0] as! FlutterStandardTypedData
    let mimeType = pigeonVar_list[1] as! String

    return ClipboardItem(
      data: data,
      mimeType: mimeType
    )
  }
  func toList() -> [Any?] {
    return [
      data,
      mimeType,
    ]
  }
}

/// Represents the complete clipboard content.
///
/// The clipboard may contain multiple items of different types.
/// For example, copying an image might also include a text representation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ClipboardContent {
  /// List of clipboard items.
  ///
  /// May be empty if the clipboard is empty or contains unsupported content.
  var items: [ClipboardItem]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClipboardContent? {
    let items = pigeonVar_list[0] as! [ClipboardItem]

    return ClipboardContent(
      items: items
    )
  }
  func toList() -> [Any?] {
    return [
      items
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ClipboardItem.fromList(self.readValue() as! [Any?])
    case 130:
      return ClipboardContent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ClipboardItem {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ClipboardContent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Host API for clipboard operations (Dart -> Native).
///
/// This API is implemented by each platform's native code and called from Dart.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PasteInputHostApi {
  /// Retrieves the current clipboard content.
  ///
  /// Returns a [ClipboardContent] containing all available clipboard items.
  /// The items are returned with their raw data and MIME types, allowing
  /// the Dart side to determine how to process them.
  ///
  /// Returns an empty [ClipboardContent] if the clipboard is empty or
  /// contains only unsupported content types.
  func getClipboardContent() throws -> ClipboardContent
  /// Clears temporary files created during paste operations.
  ///
  /// Call this periodically to free up disk space. Paste operations may
  /// create temporary files when handling image content.
  func clearTempFiles() throws
  /// Returns the platform version string.
  ///
  /// Useful for debugging and platform-specific behavior.
  /// Example: "Android 14", "iOS 17.0", "macOS 14.0"
  func getPlatformVersion() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PasteInputHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PasteInputHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PasteInputHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Retrieves the current clipboard content.
    ///
    /// Returns a [ClipboardContent] containing all available clipboard items.
    /// The items are returned with their raw data and MIME types, allowing
    /// the Dart side to determine how to process them.
    ///
    /// Returns an empty [ClipboardContent] if the clipboard is empty or
    /// contains only unsupported content types.
    let getClipboardContentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.getClipboardContent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getClipboardContentChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getClipboardContent()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getClipboardContentChannel.setMessageHandler(nil)
    }
    /// Clears temporary files created during paste operations.
    ///
    /// Call this periodically to free up disk space. Paste operations may
    /// create temporary files when handling image content.
    let clearTempFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.clearTempFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearTempFilesChannel.setMessageHandler { _, reply in
        do {
          try api.clearTempFiles()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearTempFilesChannel.setMessageHandler(nil)
    }
    /// Returns the platform version string.
    ///
    /// Useful for debugging and platform-specific behavior.
    /// Example: "Android 14", "iOS 17.0", "macOS 14.0"
    let getPlatformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.getPlatformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlatformVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlatformVersionChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API for paste event notifications (Native -> Dart).
///
/// This API is implemented in Dart and called from native code when
/// paste events are detected (e.g., through keyboard shortcuts or
/// context menu actions).
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PasteInputFlutterApiProtocol {
  /// Called when a paste event is detected on the native side.
  ///
  /// The [content] parameter contains the clipboard content at the time
  /// of the paste event. This allows Flutter to handle the pasted content
  /// immediately without additional clipboard reads.
  func onPasteDetected(content contentArg: ClipboardContent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PasteInputFlutterApi: PasteInputFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Called when a paste event is detected on the native side.
  ///
  /// The [content] parameter contains the clipboard content at the time
  /// of the paste event. This allows Flutter to handle the pasted content
  /// immediately without additional clipboard reads.
  func onPasteDetected(content contentArg: ClipboardContent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_paste_input.PasteInputFlutterApi.onPasteDetected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([contentArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
