// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.gausoft.flutter_paste_input

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Represents a single item from the clipboard.
 *
 * Each item contains raw binary data and its MIME type,
 * allowing Flutter to determine how to handle the content.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ClipboardItem (
  /**
   * Raw binary data of the clipboard item.
   *
   * For images, this contains the image bytes (PNG, JPEG, GIF, etc.).
   * For text, this contains the UTF-8 encoded string bytes.
   */
  val data: ByteArray,
  /**
   * MIME type of the clipboard item.
   *
   * Common values:
   * - "text/plain" for plain text
   * - "image/png" for PNG images
   * - "image/jpeg" for JPEG images
   * - "image/gif" for GIF images
   * - "image/webp" for WebP images
   */
  val mimeType: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClipboardItem {
      val data = pigeonVar_list[0] as ByteArray
      val mimeType = pigeonVar_list[1] as String
      return ClipboardItem(data, mimeType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      mimeType,
    )
  }
}

/**
 * Represents the complete clipboard content.
 *
 * The clipboard may contain multiple items of different types.
 * For example, copying an image might also include a text representation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ClipboardContent (
  /**
   * List of clipboard items.
   *
   * May be empty if the clipboard is empty or contains unsupported content.
   */
  val items: List<ClipboardItem>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClipboardContent {
      val items = pigeonVar_list[0] as List<ClipboardItem>
      return ClipboardContent(items)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClipboardItem.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClipboardContent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ClipboardItem -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ClipboardContent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host API for clipboard operations (Dart -> Native).
 *
 * This API is implemented by each platform's native code and called from Dart.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PasteInputHostApi {
  /**
   * Retrieves the current clipboard content.
   *
   * Returns a [ClipboardContent] containing all available clipboard items.
   * The items are returned with their raw data and MIME types, allowing
   * the Dart side to determine how to process them.
   *
   * Returns an empty [ClipboardContent] if the clipboard is empty or
   * contains only unsupported content types.
   */
  fun getClipboardContent(): ClipboardContent
  /**
   * Clears temporary files created during paste operations.
   *
   * Call this periodically to free up disk space. Paste operations may
   * create temporary files when handling image content.
   */
  fun clearTempFiles()
  /**
   * Returns the platform version string.
   *
   * Useful for debugging and platform-specific behavior.
   * Example: "Android 14", "iOS 17.0", "macOS 14.0"
   */
  fun getPlatformVersion(): String

  companion object {
    /** The codec used by PasteInputHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PasteInputHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PasteInputHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.getClipboardContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getClipboardContent())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.clearTempFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearTempFiles()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPlatformVersion())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API for paste event notifications (Native -> Dart).
 *
 * This API is implemented in Dart and called from native code when
 * paste events are detected (e.g., through keyboard shortcuts or
 * context menu actions).
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class PasteInputFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PasteInputFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /**
   * Called when a paste event is detected on the native side.
   *
   * The [content] parameter contains the clipboard content at the time
   * of the paste event. This allows Flutter to handle the pasted content
   * immediately without additional clipboard reads.
   */
  fun onPasteDetected(contentArg: ClipboardContent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_paste_input.PasteInputFlutterApi.onPasteDetected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(contentArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
