// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include "messages.g.h"

struct _FlutterPasteInputClipboardItem {
  GObject parent_instance;

  uint8_t* data;
  size_t data_length;
  gchar* mime_type;
};

G_DEFINE_TYPE(FlutterPasteInputClipboardItem, flutter_paste_input_clipboard_item, G_TYPE_OBJECT)

static void flutter_paste_input_clipboard_item_dispose(GObject* object) {
  FlutterPasteInputClipboardItem* self = FLUTTER_PASTE_INPUT_CLIPBOARD_ITEM(object);
  g_clear_pointer(&self->mime_type, g_free);
  G_OBJECT_CLASS(flutter_paste_input_clipboard_item_parent_class)->dispose(object);
}

static void flutter_paste_input_clipboard_item_init(FlutterPasteInputClipboardItem* self) {
}

static void flutter_paste_input_clipboard_item_class_init(FlutterPasteInputClipboardItemClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_paste_input_clipboard_item_dispose;
}

FlutterPasteInputClipboardItem* flutter_paste_input_clipboard_item_new(const uint8_t* data, size_t data_length, const gchar* mime_type) {
  FlutterPasteInputClipboardItem* self = FLUTTER_PASTE_INPUT_CLIPBOARD_ITEM(g_object_new(flutter_paste_input_clipboard_item_get_type(), nullptr));
  self->data = static_cast<uint8_t*>(memcpy(malloc(data_length), data, data_length));
  self->data_length = data_length;
  self->mime_type = g_strdup(mime_type);
  return self;
}

const uint8_t* flutter_paste_input_clipboard_item_get_data(FlutterPasteInputClipboardItem* self, size_t* length) {
  g_return_val_if_fail(FLUTTER_PASTE_INPUT_IS_CLIPBOARD_ITEM(self), nullptr);
  *length = self->data_length;
  return self->data;
}

const gchar* flutter_paste_input_clipboard_item_get_mime_type(FlutterPasteInputClipboardItem* self) {
  g_return_val_if_fail(FLUTTER_PASTE_INPUT_IS_CLIPBOARD_ITEM(self), nullptr);
  return self->mime_type;
}

static FlValue* flutter_paste_input_clipboard_item_to_list(FlutterPasteInputClipboardItem* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_uint8_list(self->data, self->data_length));
  fl_value_append_take(values, fl_value_new_string(self->mime_type));
  return values;
}

static FlutterPasteInputClipboardItem* flutter_paste_input_clipboard_item_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const uint8_t* data = fl_value_get_uint8_list(value0);
  size_t data_length = fl_value_get_length(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* mime_type = fl_value_get_string(value1);
  return flutter_paste_input_clipboard_item_new(data, data_length, mime_type);
}

struct _FlutterPasteInputClipboardContent {
  GObject parent_instance;

  FlValue* items;
};

G_DEFINE_TYPE(FlutterPasteInputClipboardContent, flutter_paste_input_clipboard_content, G_TYPE_OBJECT)

static void flutter_paste_input_clipboard_content_dispose(GObject* object) {
  FlutterPasteInputClipboardContent* self = FLUTTER_PASTE_INPUT_CLIPBOARD_CONTENT(object);
  g_clear_pointer(&self->items, fl_value_unref);
  G_OBJECT_CLASS(flutter_paste_input_clipboard_content_parent_class)->dispose(object);
}

static void flutter_paste_input_clipboard_content_init(FlutterPasteInputClipboardContent* self) {
}

static void flutter_paste_input_clipboard_content_class_init(FlutterPasteInputClipboardContentClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_paste_input_clipboard_content_dispose;
}

FlutterPasteInputClipboardContent* flutter_paste_input_clipboard_content_new(FlValue* items) {
  FlutterPasteInputClipboardContent* self = FLUTTER_PASTE_INPUT_CLIPBOARD_CONTENT(g_object_new(flutter_paste_input_clipboard_content_get_type(), nullptr));
  self->items = fl_value_ref(items);
  return self;
}

FlValue* flutter_paste_input_clipboard_content_get_items(FlutterPasteInputClipboardContent* self) {
  g_return_val_if_fail(FLUTTER_PASTE_INPUT_IS_CLIPBOARD_CONTENT(self), nullptr);
  return self->items;
}

static FlValue* flutter_paste_input_clipboard_content_to_list(FlutterPasteInputClipboardContent* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_ref(self->items));
  return values;
}

static FlutterPasteInputClipboardContent* flutter_paste_input_clipboard_content_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  FlValue* items = value0;
  return flutter_paste_input_clipboard_content_new(items);
}

struct _FlutterPasteInputMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(FlutterPasteInputMessageCodec, flutter_paste_input_message_codec, fl_standard_message_codec_get_type())

static gboolean flutter_paste_input_message_codec_write_flutter_paste_input_clipboard_item(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterPasteInputClipboardItem* value, GError** error) {
  uint8_t type = 129;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_paste_input_clipboard_item_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_paste_input_message_codec_write_flutter_paste_input_clipboard_content(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterPasteInputClipboardContent* value, GError** error) {
  uint8_t type = 130;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_paste_input_clipboard_content_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_paste_input_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case 129:
        return flutter_paste_input_message_codec_write_flutter_paste_input_clipboard_item(codec, buffer, FLUTTER_PASTE_INPUT_CLIPBOARD_ITEM(fl_value_get_custom_value_object(value)), error);
      case 130:
        return flutter_paste_input_message_codec_write_flutter_paste_input_clipboard_content(codec, buffer, FLUTTER_PASTE_INPUT_CLIPBOARD_CONTENT(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(flutter_paste_input_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* flutter_paste_input_message_codec_read_flutter_paste_input_clipboard_item(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterPasteInputClipboardItem) value = flutter_paste_input_clipboard_item_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(129, G_OBJECT(value));
}

static FlValue* flutter_paste_input_message_codec_read_flutter_paste_input_clipboard_content(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterPasteInputClipboardContent) value = flutter_paste_input_clipboard_content_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(130, G_OBJECT(value));
}

static FlValue* flutter_paste_input_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case 129:
      return flutter_paste_input_message_codec_read_flutter_paste_input_clipboard_item(codec, buffer, offset, error);
    case 130:
      return flutter_paste_input_message_codec_read_flutter_paste_input_clipboard_content(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(flutter_paste_input_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void flutter_paste_input_message_codec_init(FlutterPasteInputMessageCodec* self) {
}

static void flutter_paste_input_message_codec_class_init(FlutterPasteInputMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = flutter_paste_input_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = flutter_paste_input_message_codec_read_value_of_type;
}

static FlutterPasteInputMessageCodec* flutter_paste_input_message_codec_new() {
  FlutterPasteInputMessageCodec* self = FLUTTER_PASTE_INPUT_MESSAGE_CODEC(g_object_new(flutter_paste_input_message_codec_get_type(), nullptr));
  return self;
}

struct _FlutterPasteInputPasteInputHostApiGetClipboardContentResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterPasteInputPasteInputHostApiGetClipboardContentResponse, flutter_paste_input_paste_input_host_api_get_clipboard_content_response, G_TYPE_OBJECT)

static void flutter_paste_input_paste_input_host_api_get_clipboard_content_response_dispose(GObject* object) {
  FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_GET_CLIPBOARD_CONTENT_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_paste_input_paste_input_host_api_get_clipboard_content_response_parent_class)->dispose(object);
}

static void flutter_paste_input_paste_input_host_api_get_clipboard_content_response_init(FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* self) {
}

static void flutter_paste_input_paste_input_host_api_get_clipboard_content_response_class_init(FlutterPasteInputPasteInputHostApiGetClipboardContentResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_paste_input_paste_input_host_api_get_clipboard_content_response_dispose;
}

FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* flutter_paste_input_paste_input_host_api_get_clipboard_content_response_new(FlutterPasteInputClipboardContent* return_value) {
  FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_GET_CLIPBOARD_CONTENT_RESPONSE(g_object_new(flutter_paste_input_paste_input_host_api_get_clipboard_content_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom_object(130, G_OBJECT(return_value)));
  return self;
}

FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* flutter_paste_input_paste_input_host_api_get_clipboard_content_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_GET_CLIPBOARD_CONTENT_RESPONSE(g_object_new(flutter_paste_input_paste_input_host_api_get_clipboard_content_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _FlutterPasteInputPasteInputHostApiClearTempFilesResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterPasteInputPasteInputHostApiClearTempFilesResponse, flutter_paste_input_paste_input_host_api_clear_temp_files_response, G_TYPE_OBJECT)

static void flutter_paste_input_paste_input_host_api_clear_temp_files_response_dispose(GObject* object) {
  FlutterPasteInputPasteInputHostApiClearTempFilesResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_CLEAR_TEMP_FILES_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_paste_input_paste_input_host_api_clear_temp_files_response_parent_class)->dispose(object);
}

static void flutter_paste_input_paste_input_host_api_clear_temp_files_response_init(FlutterPasteInputPasteInputHostApiClearTempFilesResponse* self) {
}

static void flutter_paste_input_paste_input_host_api_clear_temp_files_response_class_init(FlutterPasteInputPasteInputHostApiClearTempFilesResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_paste_input_paste_input_host_api_clear_temp_files_response_dispose;
}

FlutterPasteInputPasteInputHostApiClearTempFilesResponse* flutter_paste_input_paste_input_host_api_clear_temp_files_response_new() {
  FlutterPasteInputPasteInputHostApiClearTempFilesResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_CLEAR_TEMP_FILES_RESPONSE(g_object_new(flutter_paste_input_paste_input_host_api_clear_temp_files_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

FlutterPasteInputPasteInputHostApiClearTempFilesResponse* flutter_paste_input_paste_input_host_api_clear_temp_files_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterPasteInputPasteInputHostApiClearTempFilesResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_CLEAR_TEMP_FILES_RESPONSE(g_object_new(flutter_paste_input_paste_input_host_api_clear_temp_files_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse, flutter_paste_input_paste_input_host_api_get_platform_version_response, G_TYPE_OBJECT)

static void flutter_paste_input_paste_input_host_api_get_platform_version_response_dispose(GObject* object) {
  FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_GET_PLATFORM_VERSION_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_paste_input_paste_input_host_api_get_platform_version_response_parent_class)->dispose(object);
}

static void flutter_paste_input_paste_input_host_api_get_platform_version_response_init(FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* self) {
}

static void flutter_paste_input_paste_input_host_api_get_platform_version_response_class_init(FlutterPasteInputPasteInputHostApiGetPlatformVersionResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_paste_input_paste_input_host_api_get_platform_version_response_dispose;
}

FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* flutter_paste_input_paste_input_host_api_get_platform_version_response_new(const gchar* return_value) {
  FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_GET_PLATFORM_VERSION_RESPONSE(g_object_new(flutter_paste_input_paste_input_host_api_get_platform_version_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(return_value));
  return self;
}

FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* flutter_paste_input_paste_input_host_api_get_platform_version_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API_GET_PLATFORM_VERSION_RESPONSE(g_object_new(flutter_paste_input_paste_input_host_api_get_platform_version_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _FlutterPasteInputPasteInputHostApi {
  GObject parent_instance;

  const FlutterPasteInputPasteInputHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(FlutterPasteInputPasteInputHostApi, flutter_paste_input_paste_input_host_api, G_TYPE_OBJECT)

static void flutter_paste_input_paste_input_host_api_dispose(GObject* object) {
  FlutterPasteInputPasteInputHostApi* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(flutter_paste_input_paste_input_host_api_parent_class)->dispose(object);
}

static void flutter_paste_input_paste_input_host_api_init(FlutterPasteInputPasteInputHostApi* self) {
}

static void flutter_paste_input_paste_input_host_api_class_init(FlutterPasteInputPasteInputHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_paste_input_paste_input_host_api_dispose;
}

static FlutterPasteInputPasteInputHostApi* flutter_paste_input_paste_input_host_api_new(const FlutterPasteInputPasteInputHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  FlutterPasteInputPasteInputHostApi* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API(g_object_new(flutter_paste_input_paste_input_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void flutter_paste_input_paste_input_host_api_get_clipboard_content_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterPasteInputPasteInputHostApi* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->get_clipboard_content == nullptr) {
    return;
  }

  g_autoptr(FlutterPasteInputPasteInputHostApiGetClipboardContentResponse) response = self->vtable->get_clipboard_content(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "PasteInputHostApi", "getClipboardContent");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PasteInputHostApi", "getClipboardContent", error->message);
  }
}

static void flutter_paste_input_paste_input_host_api_clear_temp_files_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterPasteInputPasteInputHostApi* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->clear_temp_files == nullptr) {
    return;
  }

  g_autoptr(FlutterPasteInputPasteInputHostApiClearTempFilesResponse) response = self->vtable->clear_temp_files(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "PasteInputHostApi", "clearTempFiles");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PasteInputHostApi", "clearTempFiles", error->message);
  }
}

static void flutter_paste_input_paste_input_host_api_get_platform_version_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterPasteInputPasteInputHostApi* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->get_platform_version == nullptr) {
    return;
  }

  g_autoptr(FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse) response = self->vtable->get_platform_version(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "PasteInputHostApi", "getPlatformVersion");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PasteInputHostApi", "getPlatformVersion", error->message);
  }
}

void flutter_paste_input_paste_input_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FlutterPasteInputPasteInputHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(FlutterPasteInputPasteInputHostApi) api_data = flutter_paste_input_paste_input_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(FlutterPasteInputMessageCodec) codec = flutter_paste_input_message_codec_new();
  g_autofree gchar* get_clipboard_content_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.getClipboardContent%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_clipboard_content_channel = fl_basic_message_channel_new(messenger, get_clipboard_content_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_clipboard_content_channel, flutter_paste_input_paste_input_host_api_get_clipboard_content_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* clear_temp_files_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.clearTempFiles%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) clear_temp_files_channel = fl_basic_message_channel_new(messenger, clear_temp_files_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(clear_temp_files_channel, flutter_paste_input_paste_input_host_api_clear_temp_files_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* get_platform_version_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.getPlatformVersion%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_platform_version_channel = fl_basic_message_channel_new(messenger, get_platform_version_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_platform_version_channel, flutter_paste_input_paste_input_host_api_get_platform_version_cb, g_object_ref(api_data), g_object_unref);
}

void flutter_paste_input_paste_input_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(FlutterPasteInputMessageCodec) codec = flutter_paste_input_message_codec_new();
  g_autofree gchar* get_clipboard_content_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.getClipboardContent%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_clipboard_content_channel = fl_basic_message_channel_new(messenger, get_clipboard_content_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_clipboard_content_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* clear_temp_files_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.clearTempFiles%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) clear_temp_files_channel = fl_basic_message_channel_new(messenger, clear_temp_files_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(clear_temp_files_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* get_platform_version_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_paste_input.PasteInputHostApi.getPlatformVersion%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_platform_version_channel = fl_basic_message_channel_new(messenger, get_platform_version_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_platform_version_channel, nullptr, nullptr, nullptr);
}

struct _FlutterPasteInputPasteInputFlutterApi {
  GObject parent_instance;

  FlBinaryMessenger* messenger;
  gchar *suffix;
};

G_DEFINE_TYPE(FlutterPasteInputPasteInputFlutterApi, flutter_paste_input_paste_input_flutter_api, G_TYPE_OBJECT)

static void flutter_paste_input_paste_input_flutter_api_dispose(GObject* object) {
  FlutterPasteInputPasteInputFlutterApi* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_FLUTTER_API(object);
  g_clear_object(&self->messenger);
  g_clear_pointer(&self->suffix, g_free);
  G_OBJECT_CLASS(flutter_paste_input_paste_input_flutter_api_parent_class)->dispose(object);
}

static void flutter_paste_input_paste_input_flutter_api_init(FlutterPasteInputPasteInputFlutterApi* self) {
}

static void flutter_paste_input_paste_input_flutter_api_class_init(FlutterPasteInputPasteInputFlutterApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_paste_input_paste_input_flutter_api_dispose;
}

FlutterPasteInputPasteInputFlutterApi* flutter_paste_input_paste_input_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix) {
  FlutterPasteInputPasteInputFlutterApi* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_FLUTTER_API(g_object_new(flutter_paste_input_paste_input_flutter_api_get_type(), nullptr));
  self->messenger = FL_BINARY_MESSENGER(g_object_ref(messenger));
  self->suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  return self;
}

struct _FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse {
  GObject parent_instance;

  FlValue* error;
};

G_DEFINE_TYPE(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse, flutter_paste_input_paste_input_flutter_api_on_paste_detected_response, G_TYPE_OBJECT)

static void flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_dispose(GObject* object) {
  FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_FLUTTER_API_ON_PASTE_DETECTED_RESPONSE(object);
  g_clear_pointer(&self->error, fl_value_unref);
  G_OBJECT_CLASS(flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_parent_class)->dispose(object);
}

static void flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_init(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* self) {
}

static void flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_class_init(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_dispose;
}

static FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_new(FlValue* response) {
  FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* self = FLUTTER_PASTE_INPUT_PASTE_INPUT_FLUTTER_API_ON_PASTE_DETECTED_RESPONSE(g_object_new(flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_type(), nullptr));
  if (fl_value_get_length(response) > 1) {
    self->error = fl_value_ref(response);
  }
  return self;
}

gboolean flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_is_error(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* self) {
  g_return_val_if_fail(FLUTTER_PASTE_INPUT_IS_PASTE_INPUT_FLUTTER_API_ON_PASTE_DETECTED_RESPONSE(self), FALSE);
  return self->error != nullptr;
}

const gchar* flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_code(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* self) {
  g_return_val_if_fail(FLUTTER_PASTE_INPUT_IS_PASTE_INPUT_FLUTTER_API_ON_PASTE_DETECTED_RESPONSE(self), nullptr);
  g_assert(flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 0));
}

const gchar* flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_message(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* self) {
  g_return_val_if_fail(FLUTTER_PASTE_INPUT_IS_PASTE_INPUT_FLUTTER_API_ON_PASTE_DETECTED_RESPONSE(self), nullptr);
  g_assert(flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 1));
}

FlValue* flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_details(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* self) {
  g_return_val_if_fail(FLUTTER_PASTE_INPUT_IS_PASTE_INPUT_FLUTTER_API_ON_PASTE_DETECTED_RESPONSE(self), nullptr);
  g_assert(flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_is_error(self));
  return fl_value_get_list_value(self->error, 2);
}

static void flutter_paste_input_paste_input_flutter_api_on_paste_detected_cb(GObject* object, GAsyncResult* result, gpointer user_data) {
  GTask* task = G_TASK(user_data);
  g_task_return_pointer(task, result, g_object_unref);
}

void flutter_paste_input_paste_input_flutter_api_on_paste_detected(FlutterPasteInputPasteInputFlutterApi* self, FlutterPasteInputClipboardContent* content, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data) {
  g_autoptr(FlValue) args = fl_value_new_list();
  fl_value_append_take(args, fl_value_new_custom_object(130, G_OBJECT(content)));
  g_autofree gchar* channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_paste_input.PasteInputFlutterApi.onPasteDetected%s", self->suffix);
  g_autoptr(FlutterPasteInputMessageCodec) codec = flutter_paste_input_message_codec_new();
  FlBasicMessageChannel* channel = fl_basic_message_channel_new(self->messenger, channel_name, FL_MESSAGE_CODEC(codec));
  GTask* task = g_task_new(self, cancellable, callback, user_data);
  g_task_set_task_data(task, channel, g_object_unref);
  fl_basic_message_channel_send(channel, args, cancellable, flutter_paste_input_paste_input_flutter_api_on_paste_detected_cb, task);
}

FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* flutter_paste_input_paste_input_flutter_api_on_paste_detected_finish(FlutterPasteInputPasteInputFlutterApi* self, GAsyncResult* result, GError** error) {
  g_autoptr(GTask) task = G_TASK(result);
  GAsyncResult* r = G_ASYNC_RESULT(g_task_propagate_pointer(task, nullptr));
  FlBasicMessageChannel* channel = FL_BASIC_MESSAGE_CHANNEL(g_task_get_task_data(task));
  g_autoptr(FlValue) response = fl_basic_message_channel_send_finish(channel, r, error);
  if (response == nullptr) { 
    return nullptr;
  }
  return flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_new(response);
}
