// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * FlutterPasteInputClipboardItem:
 *
 * Represents a single item from the clipboard.
 *
 * Each item contains raw binary data and its MIME type,
 * allowing Flutter to determine how to handle the content.
 */

G_DECLARE_FINAL_TYPE(FlutterPasteInputClipboardItem, flutter_paste_input_clipboard_item, FLUTTER_PASTE_INPUT, CLIPBOARD_ITEM, GObject)

/**
 * flutter_paste_input_clipboard_item_new:
 * data: field in this object.
 * data_length: length of @data.
 * mime_type: field in this object.
 *
 * Creates a new #ClipboardItem object.
 *
 * Returns: a new #FlutterPasteInputClipboardItem
 */
FlutterPasteInputClipboardItem* flutter_paste_input_clipboard_item_new(const uint8_t* data, size_t data_length, const gchar* mime_type);

/**
 * flutter_paste_input_clipboard_item_get_data
 * @object: a #FlutterPasteInputClipboardItem.
 * @length: location to write the length of this value.
 *
 * Raw binary data of the clipboard item.
 *
 * For images, this contains the image bytes (PNG, JPEG, GIF, etc.).
 * For text, this contains the UTF-8 encoded string bytes.
 *
 * Returns: the field value.
 */
const uint8_t* flutter_paste_input_clipboard_item_get_data(FlutterPasteInputClipboardItem* object, size_t* length);

/**
 * flutter_paste_input_clipboard_item_get_mime_type
 * @object: a #FlutterPasteInputClipboardItem.
 *
 * MIME type of the clipboard item.
 *
 * Common values:
 * - "text/plain" for plain text
 * - "image/png" for PNG images
 * - "image/jpeg" for JPEG images
 * - "image/gif" for GIF images
 * - "image/webp" for WebP images
 *
 * Returns: the field value.
 */
const gchar* flutter_paste_input_clipboard_item_get_mime_type(FlutterPasteInputClipboardItem* object);

/**
 * FlutterPasteInputClipboardContent:
 *
 * Represents the complete clipboard content.
 *
 * The clipboard may contain multiple items of different types.
 * For example, copying an image might also include a text representation.
 */

G_DECLARE_FINAL_TYPE(FlutterPasteInputClipboardContent, flutter_paste_input_clipboard_content, FLUTTER_PASTE_INPUT, CLIPBOARD_CONTENT, GObject)

/**
 * flutter_paste_input_clipboard_content_new:
 * items: field in this object.
 *
 * Creates a new #ClipboardContent object.
 *
 * Returns: a new #FlutterPasteInputClipboardContent
 */
FlutterPasteInputClipboardContent* flutter_paste_input_clipboard_content_new(FlValue* items);

/**
 * flutter_paste_input_clipboard_content_get_items
 * @object: a #FlutterPasteInputClipboardContent.
 *
 * List of clipboard items.
 *
 * May be empty if the clipboard is empty or contains unsupported content.
 *
 * Returns: the field value.
 */
FlValue* flutter_paste_input_clipboard_content_get_items(FlutterPasteInputClipboardContent* object);

G_DECLARE_FINAL_TYPE(FlutterPasteInputMessageCodec, flutter_paste_input_message_codec, FLUTTER_PASTE_INPUT, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(FlutterPasteInputPasteInputHostApi, flutter_paste_input_paste_input_host_api, FLUTTER_PASTE_INPUT, PASTE_INPUT_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(FlutterPasteInputPasteInputHostApiGetClipboardContentResponse, flutter_paste_input_paste_input_host_api_get_clipboard_content_response, FLUTTER_PASTE_INPUT, PASTE_INPUT_HOST_API_GET_CLIPBOARD_CONTENT_RESPONSE, GObject)

/**
 * flutter_paste_input_paste_input_host_api_get_clipboard_content_response_new:
 *
 * Creates a new response to PasteInputHostApi.getClipboardContent.
 *
 * Returns: a new #FlutterPasteInputPasteInputHostApiGetClipboardContentResponse
 */
FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* flutter_paste_input_paste_input_host_api_get_clipboard_content_response_new(FlutterPasteInputClipboardContent* return_value);

/**
 * flutter_paste_input_paste_input_host_api_get_clipboard_content_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to PasteInputHostApi.getClipboardContent.
 *
 * Returns: a new #FlutterPasteInputPasteInputHostApiGetClipboardContentResponse
 */
FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* flutter_paste_input_paste_input_host_api_get_clipboard_content_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(FlutterPasteInputPasteInputHostApiClearTempFilesResponse, flutter_paste_input_paste_input_host_api_clear_temp_files_response, FLUTTER_PASTE_INPUT, PASTE_INPUT_HOST_API_CLEAR_TEMP_FILES_RESPONSE, GObject)

/**
 * flutter_paste_input_paste_input_host_api_clear_temp_files_response_new:
 *
 * Creates a new response to PasteInputHostApi.clearTempFiles.
 *
 * Returns: a new #FlutterPasteInputPasteInputHostApiClearTempFilesResponse
 */
FlutterPasteInputPasteInputHostApiClearTempFilesResponse* flutter_paste_input_paste_input_host_api_clear_temp_files_response_new();

/**
 * flutter_paste_input_paste_input_host_api_clear_temp_files_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to PasteInputHostApi.clearTempFiles.
 *
 * Returns: a new #FlutterPasteInputPasteInputHostApiClearTempFilesResponse
 */
FlutterPasteInputPasteInputHostApiClearTempFilesResponse* flutter_paste_input_paste_input_host_api_clear_temp_files_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse, flutter_paste_input_paste_input_host_api_get_platform_version_response, FLUTTER_PASTE_INPUT, PASTE_INPUT_HOST_API_GET_PLATFORM_VERSION_RESPONSE, GObject)

/**
 * flutter_paste_input_paste_input_host_api_get_platform_version_response_new:
 *
 * Creates a new response to PasteInputHostApi.getPlatformVersion.
 *
 * Returns: a new #FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse
 */
FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* flutter_paste_input_paste_input_host_api_get_platform_version_response_new(const gchar* return_value);

/**
 * flutter_paste_input_paste_input_host_api_get_platform_version_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to PasteInputHostApi.getPlatformVersion.
 *
 * Returns: a new #FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse
 */
FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* flutter_paste_input_paste_input_host_api_get_platform_version_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * FlutterPasteInputPasteInputHostApiVTable:
 *
 * Table of functions exposed by PasteInputHostApi to be implemented by the API provider.
 */
typedef struct {
  FlutterPasteInputPasteInputHostApiGetClipboardContentResponse* (*get_clipboard_content)(gpointer user_data);
  FlutterPasteInputPasteInputHostApiClearTempFilesResponse* (*clear_temp_files)(gpointer user_data);
  FlutterPasteInputPasteInputHostApiGetPlatformVersionResponse* (*get_platform_version)(gpointer user_data);
} FlutterPasteInputPasteInputHostApiVTable;

/**
 * flutter_paste_input_paste_input_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the PasteInputHostApi API.
 */
void flutter_paste_input_paste_input_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FlutterPasteInputPasteInputHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * flutter_paste_input_paste_input_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the PasteInputHostApi API.
 */
void flutter_paste_input_paste_input_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

G_DECLARE_FINAL_TYPE(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse, flutter_paste_input_paste_input_flutter_api_on_paste_detected_response, FLUTTER_PASTE_INPUT, PASTE_INPUT_FLUTTER_API_ON_PASTE_DETECTED_RESPONSE, GObject)

/**
 * flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_is_error:
 * @response: a #FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse.
 *
 * Checks if a response to PasteInputFlutterApi.onPasteDetected is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_is_error(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* response);

/**
 * flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_code:
 * @response: a #FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_code(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* response);

/**
 * flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_message:
 * @response: a #FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_message(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* response);

/**
 * flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_details:
 * @response: a #FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* flutter_paste_input_paste_input_flutter_api_on_paste_detected_response_get_error_details(FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* response);

/**
 * FlutterPasteInputPasteInputFlutterApi:
 *
 * Flutter API for paste event notifications (Native -> Dart).
 *
 * This API is implemented in Dart and called from native code when
 * paste events are detected (e.g., through keyboard shortcuts or
 * context menu actions).
 */

G_DECLARE_FINAL_TYPE(FlutterPasteInputPasteInputFlutterApi, flutter_paste_input_paste_input_flutter_api, FLUTTER_PASTE_INPUT, PASTE_INPUT_FLUTTER_API, GObject)

/**
 * flutter_paste_input_paste_input_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the PasteInputFlutterApi API.
 *
 * Returns: a new #FlutterPasteInputPasteInputFlutterApi
 */
FlutterPasteInputPasteInputFlutterApi* flutter_paste_input_paste_input_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * flutter_paste_input_paste_input_flutter_api_on_paste_detected:
 * @api: a #FlutterPasteInputPasteInputFlutterApi.
 * @content: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Called when a paste event is detected on the native side.
 *
 * The [content] parameter contains the clipboard content at the time
 * of the paste event. This allows Flutter to handle the pasted content
 * immediately without additional clipboard reads.
 */
void flutter_paste_input_paste_input_flutter_api_on_paste_detected(FlutterPasteInputPasteInputFlutterApi* api, FlutterPasteInputClipboardContent* content, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * flutter_paste_input_paste_input_flutter_api_on_paste_detected_finish:
 * @api: a #FlutterPasteInputPasteInputFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a flutter_paste_input_paste_input_flutter_api_on_paste_detected() call.
 *
 * Returns: a #FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse or %NULL on error.
 */
FlutterPasteInputPasteInputFlutterApiOnPasteDetectedResponse* flutter_paste_input_paste_input_flutter_api_on_paste_detected_finish(FlutterPasteInputPasteInputFlutterApi* api, GAsyncResult* result, GError** error);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
